pool_specification:
  id: sraassembly-pool
  vm_configuration:
    platform_image:
      publisher: Canonical
      offer: UbuntuServer
      sku: 18.04-LTS
  vm_count:
    dedicated: 2
    low_priority: 0
  vm_size: STANDARD_E48_V3
  max_tasks_per_node: 1
  autoscale:
    evaluation_interval: 00:30:00
    scenario:
      name: active_tasks
      maximum_vm_count:
        dedicated: 0
        low_priority: 0
      maximum_vm_increment_per_evaluation:
        dedicated: -1
        low_priority: -1
